import type { NextPage } from "next";
import Head from "next/head";
import Detection from "../components/Detection";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Yolo OD App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Detection />
    </div>
  );
};

export default Home;
